CineRating/Models/Filmes.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace CineRating.Models {
    public class Filmes {


        public Filmes() {

            ListaDeGeneros = new HashSet<Generos>();
            ListaDePersonagens = new HashSet<Personagem>();
            ListaDeComentarios = new HashSet<Comentario>();

        }

        [Key]
        public int ID { get; set; }

        [Display(Name = "Título")]
        [Required(ErrorMessage = "O {0} é obrigatório!")]
        public string Titulo { get; set; }

        [Display(Name = "Descrição")]
        [Required(ErrorMessage = "A {0} é obrigatória!")]
        public string Descricao { get; set; }

        [Display(Name = "Duração")]
        [Required(ErrorMessage = "A {0} é obrigatória!")]
        public int TempoExecucao { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "A {0} é obrigatória!")]
        [Display(Name = "Data de Lançamento")]
        public DateTime DataLancamento { get; set; }

        public string Imagem { get; set; }

        [RegularExpression("^(http(s)?://)((w){3}.)youtube(.com)(/)embed?/.+", ErrorMessage = "O {0} tem de ter o formato www.youtube.com/embed/'id'")]
        [Required(ErrorMessage = "O {0} é obrigatório!")]
        public string Video { get; set; }


        //FK Diretor
        [ForeignKey("Realizador")]
        public int RealizadorFK { get; set; }
        public virtual Realizadores Realizador { get; set; }


        public virtual ICollection<Generos> ListaDeGeneros { get; set; }
        public virtual ICollection<Personagem> ListaDePersonagens { get; set; }
        public virtual ICollection<Comentario> ListaDeComentarios { get; set; }
    }
}

CineRating/Controllers/ComentariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CineRating.Models;

namespace CineRating.Controllers {
    public class ComentariosController : Controller {
        private ApplicationDbContext db = new ApplicationDbContext();



        // POST: Comentarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FilmeFK,Texto,")] Comentario comentario) {

            var userID = GetID();

            comentario.UserFK = userID;
            comentario.DataComentario = DateTime.Now;




            if (ModelState.IsValid) {
                db.Comentario.Add(comentario);
                db.SaveChanges();
                return RedirectToAction("Details", "Filmes", new { id = comentario.FilmeFK });
            }

            ViewBag.FilmeFK = new SelectList(db.Filmes, "ID", "Titulo", comentario.FilmeFK);
            ViewBag.UserFK = new SelectList(db.Utilizadores, "ID", "NomeUtilizador", comentario.UserFK);
            return View(comentario);
        }

        [Authorize(Roles = "Administradores,Gestores,Utilizadores")]
        // GET: Comentarios/Edit/5
        public ActionResult Edit(int? id) {
            var userID = GetID();
            if (id == null) {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return RedirectToAction("Index");
            }
            Comentario comentario = db.Comentario.Find(id);
            if (comentario == null || comentario.UserFK != userID) {
                //return HttpNotFound();
                return RedirectToAction("Index");
            }
            ViewBag.FilmeFK = new SelectList(db.Filmes, "ID", "Titulo", comentario.FilmeFK);
            ViewBag.UserFK = new SelectList(db.Utilizadores, "ID", "NomeUtilizador", comentario.UserFK);
            return View(comentario);
        }

        // POST: Comentarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Texto")] Comentario comentario, int filmeID, int userID) {

            comentario.FilmeFK = filmeID;
            comentario.UserFK = userID;
            comentario.DataComentario = DateTime.Now;

            if (ModelState.IsValid) {
                db.Entry(comentario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details/" + filmeID, "Filmes");
            }
            ViewBag.FilmeFK = new SelectList(db.Filmes, "ID", "Titulo", comentario.FilmeFK);
            ViewBag.UserFK = new SelectList(db.Utilizadores, "ID", "NomeUtilizador", comentario.UserFK);
            return View(comentario);
        }

        [Authorize(Roles = "Administradores,Gestores,Utilizadores")]
        // GET: Comentarios/Delete/5
        public ActionResult Delete(int? id) {
            var userID = GetID();
            if (id == null) {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return RedirectToAction("Index");
            }
            Comentario comentario = db.Comentario.Find(id);
            if (comentario != null && (comentario.UserFK == userID || User.IsInRole("Administradores"))) {
                //return HttpNotFound();
                return View(comentario);
            }
            return RedirectToAction("Index");
        }

        // POST: Comentarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int filmeID) {
            Comentario comentario = db.Comentario.Find(id);
            db.Comentario.Remove(comentario);
            db.SaveChanges();
            return RedirectToAction("Details/" + filmeID, "Filmes");
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //função auxiliar para fazer a ligação entre a tabela do ASPNET de utilizadores registados com a tabela utilizadores criada
        public int GetID() {
            var userIDList = db.Utilizadores.Where(u => u.NomeUtilizador.Equals(User.Identity.Name));
            var userID = 0;
            foreach (var item in userIDList) {
                userID = item.ID;
            }
            return userID;
        }
    }
}

CineRating/Controllers/PersonagensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CineRating.Models;

namespace CineRating.Controllers {
    public class PersonagensController : Controller {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Personagens
        /// <summary>
        /// Mostra as personagens que entram num filme
        /// </summary>
        /// <returns></returns>
        public ActionResult Index() {
            var aux = Convert.ToInt32(Session["filmeID"]);
            if (aux != 0) {
                var personagem = db.Personagem.Where(p => p.MovieFK.Equals(aux))
                .Include(p => p.ID_Ator)
                .Include(p => p.ID_Filme);
                Session["filmeID"] = 0;
                return View(personagem.ToList());
            }
            return RedirectToAction("Index", "Filmes");
        }



        // GET: Personagens/Create
        [Authorize(Roles = "Administradores,Gestores")]
        public ActionResult Create(int? filmeID) {
            if (filmeID != null) {
                ViewBag.AtorFK = new SelectList(db.Atores, "ID", "Nome");
                ViewBag.MovieFK = new SelectList(db.Filmes, "ID", "Titulo");
                return View();
            }
            return RedirectToAction("Index", "Filmes");
        }

        // POST: Personagens/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,AtorFK,Role")] Personagem personagem, int? filmeID) {
            if (filmeID != null) {
                personagem.MovieFK = (int)filmeID;
                if (ModelState.IsValid) {
                    db.Personagem.Add(personagem);
                    db.SaveChanges();
                    return RedirectToAction("Details", "Filmes", new { id = filmeID });
                }

                ViewBag.AtorFK = new SelectList(db.Atores, "ID", "Nome", personagem.AtorFK);
                ViewBag.MovieFK = new SelectList(db.Filmes, "ID", "Titulo", personagem.MovieFK);
                return View(personagem);
            }
            return RedirectToAction("Index", "Filmes");
        }



        // GET: Personagens/Delete/5
        [Authorize(Roles = "Administradores,Gestores")]
        public ActionResult Delete(int? id) {
            if (id == null) {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return RedirectToAction("Index");
            }
            Personagem personagem = db.Personagem.Find(id);
            if (personagem == null) {
                //return HttpNotFound();
                return RedirectToAction("Index");
            }
            return View(personagem);
        }

        // POST: Personagens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id) {
            Personagem personagem = db.Personagem.Find(id);
            db.Personagem.Remove(personagem);
            db.SaveChanges();
            return RedirectToAction("Details", "Filmes", new { id = personagem.MovieFK });
        }

        protected override void Dispose(bool disposing) {
            if (disposing) {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CineRating/Views/Filmes/Create.cshtml
@model CineRating.Models.Filmes

@{
    ViewBag.Title = "Adicionar Filme";
}

<h2>Adicionar Filme</h2>
<hr />

@*IMPORTANTE*@
@using (Html.BeginForm("Create", "Filmes", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @*IMPORTANTE*@
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control", @style = "max-width:500px;", @placeholder = "Título do Filme" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Descricao, new { @class = "form-control", maxlength = "500", @style = "resize:none; width:100%; max-width:500px; height:150px;", @placeholder = "Sinopse do Filme" })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TempoExecucao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TempoExecucao, new { htmlAttributes = new { @class = "form-control", @style = "max-width:100px;", @placeholder = "Minutos" } })
                @Html.ValidationMessageFor(model => model.TempoExecucao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataLancamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input class="form-control" type="date" style="width:160px;" name="DataLanc" max=@DateTime.Now.ToString("yyyy-MM-dd") />
                @Html.ValidationMessageFor(model => model.DataLancamento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                <input type="file" name="fileUploadImagem" style="color:blue;" accept=".jpg" />
                @Html.ValidationMessageFor(model => model.Imagem, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Video, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Video, new { htmlAttributes = new { @class = "form-control", @style = "max-width:500px;", @placeholder = "https://www.youtube.com/embed/ue80QwXMRHg" } })
                @Html.ValidationMessageFor(model => model.Video, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <lbl class="control-label col-md-2" style="font-weight:bold">Realizador</lbl>
            <div class="col-md-10">
                @Html.DropDownList("RealizadorFK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RealizadorFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <lbl class="control-label col-md-2" style="font-weight:bold">Géneros</lbl>
            <div class="col-md-10">
                @foreach (Generos item in ViewBag.generosList) {
                    <span>@item.Nome</span>
                    <input type="checkbox" name="generoID" value="@item.ID" class="checkbox-inline" style="margin-right:10px;" />
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Adicionar" class="btn btn-default" />
                <a class="btn btn-default" href="@Url.Action("Index","Filmes")">Cancelar</a>
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CineRating/Views/Filmes/Delete.cshtml
@model CineRating.Models.Filmes

@{
    ViewBag.Title = "Eliminar Filme";
}


<h3>Tem a certeza que quer eliminar este filme?</h3>
<div>
    <hr />
    @*Apresenta mensagens de erro*@
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div>
        <h2>@Html.DisplayFor(model => model.Titulo)</h2>
        <img src="~/imagens/filmes/@Model.Imagem" height="300" />
    </div>


    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        <br />
        <div class="form-actions no-color">
            <input type="submit" value="Apagar" class="btn btn-danger" />
            <a class="btn btn-default" href="@Url.Action("Index","Filmes")">Cancelar</a>
        </div>
    }
</div>

CineRating/Views/Filmes/Details.cshtml
@model CineRating.Models.Filmes

@{
    ViewBag.Title = Model.Titulo;
}

@*<h2>Details</h2>*@


<div style="border:10px thin; box-shadow: 0px 0px 8px rgba(0,0,0,0.7); width:1140px;">
    <div style="background-color:#333; padding-top:23px; padding-bottom:5px;">
        <div style="margin-left:15px;">
            <div style="float:right; margin-right:20px;">
                <h3 style="color:lightgray; display:inline;">Realizador:</h3> <a href="@Url.Action("Details", "Realizadores", new { id = Model.RealizadorFK })"><h3 style="display:inline">@Model.Realizador.Nome</h3></a>
            </div>
            <h1>@Html.DisplayFor(model => model.Titulo)</h1>
            <h3 style="color:lightgray">@Model.DataLancamento.ToString("dd-MM-yyyy")</h3>
            <div style="float:right; margin-right:20px;">
                @foreach (var gen in Model.ListaDeGeneros) {
                    <h4 style="display:inline; color:lightgray;">
                        | @Html.DisplayFor(modelItem => gen.Nome)
                    </h4>
                }
            </div>
            <h3 style="color:lightgray">Duração: @Html.DisplayFor(model => model.TempoExecucao) minutos</h3>

            @if (User.IsInRole("Administradores") || User.IsInRole("Gestores")) {
                @Html.ActionLink("Editar", "Edit", new { id = Model.ID }, new { @class = "btn btn-default" })<span>   </span>
                @Html.ActionLink("Eliminar", "Delete", new { id = Model.ID }, new { @class = "btn btn-default" })
            }

        </div>
    </div>

    <div style="display:flex; flex-direction:row; flex-wrap:wrap;">
        <img class="filmeImg" src="~/imagens/filmes/@Model.Imagem" style="height:426px; width:288px;" />
        <iframe class="filmeTrailer" src="@Model.Video" style="height:426px; width:852px;"></iframe>
    </div>

    <div style="background-color:white;">
        <div style="margin-left:20px; margin-right:20px; margin-bottom:20px;">
            <span style="font-size:large; color:black;">
                @Model.Descricao
            </span>
        </div>
    </div>
</div>
<h2>Personagens</h2>

@if (User.IsInRole("Administradores") || User.IsInRole("Gestores")) {
    <a href="@Url.Action("Create", "Personagens", new {filmeID = Model.ID})">Adicionar Personagem</a>
}

<br />
<br />
<div class="row" style="display:flex; flex-direction:row; flex-wrap:wrap;">
    @foreach (var pers in Model.ListaDePersonagens) {
        <div style="text-align:center">
            <span style="font-weight:bold">@pers.Role</span>
            @if (User.IsInRole("Administradores") || User.IsInRole("Gestores")) {
                <a href="@Url.Action("Delete", "Personagens", new { id = pers.ID })" style="color: red;">  <span title="Remover Personagem" class="glyphicon glyphicon-remove"></span></a>
            }
            @Html.Action("AtoresFilme", "Atores", new { filmeID = pers.AtorFK })
        </div>
    }
</div>
<h2>Comentários</h2>
<div>
    @foreach (var coment in Model.ListaDeComentarios) {
        <div style="border-top:1px solid; margin-bottom:20px;">
            <span style="font-size:large; font-weight:bold">@coment.ID_User.Nome</span>
            <br />
            <b>
                @coment.DataComentario.ToString("dd-MM-yyyy")
            </b>
            <br />
            <div style="margin: 10px 0 20px">
                @coment.Texto
            </div>
            @if (Request.IsAuthenticated && (User.IsInRole("Administradores") || User.Identity.Name.Equals(coment.ID_User.NomeUtilizador))) {
                <div style="text-align:right;">
                    <a href="@Url.Action("Delete", "Comentarios", new { id = coment.ID, filmeID = coment.FilmeFK })">Eliminar Comentário</a>
                    @if (User.Identity.Name.Equals(coment.ID_User.NomeUtilizador)) {
                        <span>|</span> <a href="@Url.Action("Edit", "Comentarios", new { id = coment.ID, filmeID = coment.FilmeFK, userID = coment.UserFK })"> Editar Comentário </a>
                    }
                    <br />
                </div>
            }
        </div>
    }
</div>
<div>
    @if (Request.IsAuthenticated) {
        @Html.Partial("_AdicionarComentario", new CineRating.Models.Comentario { FilmeFK = Model.ID })
    } else {
        <p style="font-weight:bold; color:red; font-size:x-large">Para poder comentar tem de fazer login!</p>
    }
</div>

CineRating/Views/Filmes/Edit.cshtml
@model CineRating.Models.Filmes
@{
    ViewBag.Title = "Editar Filme";
}
<h2>Editar filme</h2>

@*IMPORTANTE*@
@using (Html.BeginForm("Edit", "Filmes", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @*IMPORTANTE*@
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @*IMPORTANTE*@
        @Html.HiddenFor(model => model.Imagem)
        @*IMPORTANTE*@
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control", @style = "max-width:500px;", @placeholder = "Título do Filme" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Descricao, new { @class = "form-control", maxlength = "500", @style = "resize:none; width:100%; max-width:500px; height:150px;", @placeholder = "Sinopse do Filme" })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.TempoExecucao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TempoExecucao, new { htmlAttributes = new { @class = "form-control", @style = "max-width:100px;", @placeholder = "Minutos" } })
                @Html.ValidationMessageFor(model => model.TempoExecucao, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.DataLancamento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataLancamento, new { htmlAttributes = new { @class = "form-control", style = "width:160px", type = "date", value = Model.DataLancamento.ToString("yyyy-MM-dd"), max = DateTime.Now.ToString("yyyy-MM-dd") } })
                @Html.ValidationMessageFor(model => model.DataLancamento, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Imagem, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Imagem, new { htmlAttributes = new { @class = "form-control" } })*@
                <a href="~/imagens/filmes/@Model.Imagem" target="_blank">
                    <img src="~/imagens/filmes/@Model.Imagem" height="150" />
                </a>
                <input type="file" name="fileUploadImagem" style="color:blue; margin-top:1%" accept=".jpg" />
                @Html.ValidationMessageFor(model => model.Imagem, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Video, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Video, new { htmlAttributes = new { @class = "form-control", @style = "max-width:500px;", @placeholder = "https://www.youtube.com/embed/ue80QwXMRHg" } })
                @Html.ValidationMessageFor(model => model.Video, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <lbl class="control-label col-md-2" style="font-weight:bold">Realizador</lbl>
            <div class="col-md-10">
                @Html.DropDownList("RealizadorFK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RealizadorFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <lbl class="control-label col-md-2" style="font-weight:bold">Géneros</lbl>
            <div class="col-md-10">
                @foreach (Generos item in ViewBag.generosList) {
                    <span>@item.Nome</span>
                    if (Model.ListaDeGeneros.Contains(item)) {
                        <input type="checkbox" name="generoID" value="@item.ID" class="checkbox-inline" style="margin-right:10px;" checked />
                    } else {
                        <input type="checkbox" name="generoID" value="@item.ID" class="checkbox-inline" style="margin-right:10px;" />
                    }
                }
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
                <a class="btn btn-default" href="@Url.Action("Index","Filmes")">Cancelar</a>
            </div>
        </div>
    </div>
}
@*<div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CineRating/Views/Filmes/FilmeAtores.cshtml
@model IEnumerable<CineRating.Models.Filmes>



@foreach (var item in Model) {
    <div class="filmesImg" style="margin:25px;">
        <p style="font-size:14px; font-weight:bold;">@item.Titulo</p>
        <a href="@Url.Action("Details", "Filmes", new { id = item.ID })">
            <img src="~/imagens/filmes/@item.Imagem" style="height:300px" />
        </a>
    </div>
}

CineRating/Views/Filmes/FilmeRealizadores.cshtml
@model IEnumerable<CineRating.Models.Filmes>

@foreach (var item in Model) {
<div class="filmesImg" style="margin:15px;">
    <p style="font-size:14px; font-weight:bold;">@item.Titulo</p>
    <a href="@Url.Action("Details", "Filmes", new { id = item.ID })">
        <img src="~/imagens/filmes/@item.Imagem" style="height:300px" />
    </a>
</div>
}

CineRating/Views/Filmes/Index.cshtml
@model IEnumerable<CineRating.Models.Filmes>

@{
    ViewBag.Title = "CineRating";
}


@using (Html.BeginForm()) {
    <div style="text-align:center">
        @Html.TextBox("pesq", "", new { @id = "tituloFilme", @autocomplete = "off", @placeholder = "Pesquisar Filmes", style = "width:500px; height:35px; max-width:none;" })
        <input type="submit" class="btn btn-default" value="Pesquisar" style="display:none;" />
    </div>
}


<div style="display:flex; flex-direction:row; flex-wrap:wrap;">
    @foreach (var item in Model) {
        <div style="text-align:center; width:380px;">
            <br />
            <p style="font-weight:bold; font-size:large">@item.Titulo</p>
            <a href="@Url.Action("Details", "Filmes", new { id = item.ID})">
                <img src="~/imagens/filmes/@item.Imagem" style="margin:15px; height:500px; width:338px;" />
            </a>

        </div>

    }
</div>



<link href="~/Content/themes/base/jquery-ui.css"
      rel="stylesheet"
      type="text/css" />


@section Scripts {
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#tituloFilme').autocomplete({
                source: '/Filmes/GetFilmes'
            });
        });
    </script>
}

CineRating/Views/Filmes/_AdicionarComentario.cshtml
@model CineRating.Models.Comentario

@using (Html.BeginForm("Create", "Comentarios")) {

    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.FilmeFK)

    <div class="form-group">
        @Html.LabelFor(model => model.Texto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.Texto, new { @class = "form-control", maxlength = "500", @style = "resize:none; width:100%; max-width:700px; height:150px;" })
            @Html.ValidationMessageFor(model => model.Texto, "", new { @class = "text-danger" })
            <br />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Adicionar" class="btn btn-default" />
        </div>
    </div>




}